import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navigation from '../components/Navigation'
import Introduction from '../components/Introduction'
import HeadTag from '../components/HeadTag'
import Link from 'next/link'


import "./api/unsplash"
import unsplash from './api/unsplash'

import React, {useState} from 'react';

export default function Home({unsplash_data, spotify_data}) {
    // console.log(unsplash_data.downloads)
    
  return (
    <>
        <div className="w-2/3 mx-auto bg-first">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                {/* <HeadTag /> */}
            </Head>
            <Navigation />
        </div>
        <div className="h-12 bg-second w-full flex items-center">
            <div className="w-2/3 mx-auto ">
            <SpotifyPlaying spotify_data={spotify_data} />
            </div>
        </div>
        <div className="w-2/3 mx-auto bg-first">
            <Introduction />
            <a classname="" href="/notes">Notes</a>
            <h2 className="text-3xl font-bold underline"> Hello World!</h2>
        </div>
    </>
  )
}

function SpotifyPlaying({spotify_data}) {
    if(spotify_data.isPlaying == false) {
        return <a href="https://spotify.com"><i class="fa-brands fa-spotify mr-2"></i><span className="font-bold">Not Playing</span></a>
    }
    else
        return <a href={spotify_data.songUrl}><i class="fa-brands fa-spotify mr-2"></i><span className="font-bold mr-2">Now Playing</span>{spotify_data.artist} - {spotify_data.title}</a>
}
export async function getServerSideProps() {
    // Fetch data from external API
    const unsplash = await fetch(`http://localhost:3000/api/unsplash`)
    const spotify = await fetch(`http://localhost:3000/api/spotify`)
    
    const unsplash_data = await unsplash.json()
    const spotify_data = await spotify.json()
    
  
    // Pass data to the page via props
    return { props: { unsplash_data, spotify_data  } }
  }
